[camera]
aspect_ratio = "square"
image_width = 400
samples = 100
max_bounces = 50
threads = 4
fov = 80.0
look_from = [0.0, 0.0, 9.0]
look_at = [0.0, 0.0, 0.0]
vup = [0.0, 1.0, 0.0]
background = [0.70, 0.80, 0.99]

[[objects]]
shape = "quad"
position = [-3.0,-2.0, 5.0]
u = [0.0, 0.0,-4.0]
v = [0.0, 4.0, 0.0]
material = "lambertian"
albedo = [1.0, 0.2, 0.2]

[[objects]]
shape = "quad"
position = [-2.0,-2.0, 0.0]
u = [4.0, 0.0, 0.0]
v = [0.0, 4.0, 0.0]
material = "lambertian"
albedo = [0.2, 1.0, 0.2]

[[objects]]
shape = "quad"
position = [3.0,-2.0, 1.0]
u = [0.0, 0.0, 4.0]
v = [0.0, 4.0, 0.0]
material = "lambertian"
albedo = [0.2, 0.2, 1.0]

[[objects]]
shape = "quad"
position = [-2.0,3.0, 1.0]
u = [4.0, 0.0, 0.0]
v = [0.0, 0.0, 4.0]
material = "lambertian"
albedo = [1.0, 0.5, 0.0]

[[objects]]
shape = "quad"
position = [-2.0,-3.0, 5.0]
u = [4.0, 0.0, 0.0]
v = [0.0, 0.0, -4.0]
material = "lambertian"
albedo = [0.2, 0.8, 0.8]
