[camera]
aspect_ratio = "widescreen"
image_width = 400
samples = 100
max_bounces = 50
threads = 4
fov = 20.0
look_from = [13.0, 2.0, 3.0]
look_at = [0.0, 0.0, 0.0]
vup = [0.0, 1.0, 0.0]

[[objects]]
shape = "sphere"
position = [0.0, -10.0, 0.0]
radius = 10.0
material = "checkered"
scale = 0.32
even = [0.2, 0.3, 0.1]
odd = [0.9, 0.9, 0.9]

[[objects]]
shape = "sphere"
position = [0.0, 10.0, 0.0]
radius = 10.0
material = "checkered"
scale = 0.32
even = [0.2, 0.3, 0.1]
odd = [0.9, 0.9, 0.9]
