[camera]
aspect_ratio = "square"
image_width = 600
samples = 200
max_bounces = 50
threads = 4
fov = 40
look_from = [278.0, 278.0, -800.0]
look_at = [278.0, 278.0, 0.0]
vup = [0.0, 1.0, 0.0]

# Left Wall
[[objects]]
shape = "quad"
position = [555.0, 0.0, 0.0]
u = [0.0, 555.0, 0.0]
v = [0.0, 0.0, 555.0]
material = "lambertian"
albedo = [0.12, 0.45, 0.15]

# Right Wall
[[objects]]
shape = "quad"
position = [0.0, 0.0, 0.0]
u = [0.0, 555.0, 0.0]
v = [0.0, 0.0, 555.0]
material = "lambertian"
albedo = [0.65, 0.05, 0.05]

# Floor
[[objects]]
shape = "quad"
position = [0.0, 0.0, 0.0]
u = [555.0, 0.0, 0.0]
v = [0.0, 0.0, 555.0]
material = "lambertian"
albedo = [0.73, 0.73, 0.73]

# Ceiling
[[objects]]
shape = "quad"
position = [555.0, 555.0, 555.0]
u = [-555.0, 0.0, 0.0]
v = [0.0, 0.0, -555.0]
material = "lambertian"
albedo = [0.73, 0.73, 0.73]

# Back Wall
[[objects]]
shape = "quad"
position = [0.0, 0.0, 555.0]
u = [555.0, 0.0, 0.0]
v = [0.0, 555.0, 0.0]
material = "lambertian"
albedo = [0.73, 0.73, 0.73]

# Light
[[objects]]
shape = "quad"
position = [343.0, 554.0, 332.0]
u = [-130.0, 0.0, 0.0]
v = [0.0, 0.0, -105.0]
material = "light"
emit = [15.0, 15.0, 15.0]
