[camera]
aspect_ratio = "widescreen"
image_width = 600
samples = 3000
max_bounces = 64
fov = 40
look_from = [7.0, 5.0, 3.0]
look_at = [0.0, 2.2, 0.0]
vup = [0.0, 1.0, 0.0]


# Cube
[[objects]]
shape = "cube"
a = [-1.0, -1.0, -1.0]
b = [1.0, 1.0, 1.0]
material = "lambertian"
albedo = [0.73, 0.73, 0.73]

[[objects.transform]]
type = "rotate"
degrees = 15.0
axis = "y"

[[objects.transform]]
type = "translate"
offset = [0.0, 2.0, 0.0]

# Floor
[[objects]]
shape = "quad"
position = [500.0, 0.0, 500.0]
u = [-1000.0, 0.0, 0.0]
v = [0.0, 0.0, -1000.0]
scale = 0.002
material = "checkered"
even = [0.2, 0.3, 0.1]
odd = [0.9, 0.9, 0.9]

# Light
[[objects]]
shape = "quad"
position = [5.0, 0.0, 5.0]
u = [-10.0, 0.0, 0.0]
v = [0.0, 0.0, -10.0]
material = "light"
emit = [3.0, 3.0, 3.0]

[[objects.transform]]
type = "translate"
offset = [0.0, 10.0, 0.0]

[[objects.transform]]
type = "rotate"
degrees = -30.0
axis = "z"
