[camera]
aspect_ratio = "widescreen"
image_width = 400
samples = 100
max_bounces = 50
threads = 4
fov = 20.0
look_from = [0.0, 0.0, 12.0]
look_at = [0.0, 0.0, 0.0]
vup = [0.0, 1.0, 0.0]

[[objects]]
shape = "sphere"
position = [0.0, 0.0, 0.0]
radius = 2
material = "texture"
file = "earthmap.jpg"
